# ai/severity_model.py
# MERLIN — Medical Emergency Routing and Live Intelligence Network
# Severity Model — XGBoost classifier for emergency severity prediction
#
# This model is the AI brain of MERLIN.
# It learns from simulation data to predict emergency severity
# from available features at the time of a 911 call.
#
# In a real deployment, this model would be retrained
# periodically on real dispatch records as they accumulate.
# In our simulation, it trains on synthetic data generated
# by the simulation runner.

import numpy as np
import pandas as pd
import pickle
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    f1_score,
    accuracy_score
)
from sklearn.preprocessing import LabelEncoder
import xgboost as xgb

from core.grid import SEVERITY_NAMES

# ── Model Configuration ──────────────────────────────────────────
MODEL_SAVE_PATH   = 'data/synthetic/severity_model.pkl'
RESULTS_CSV_PATH  = 'data/synthetic/simulation_results.csv'

# Features the model uses — these are the X inputs
# Exactly the features stored in DispatchDecision.features
FEATURE_COLUMNS = [
    'severity',            # ground truth label — NOT a feature
                           # listed here for reference only
    'emergency_type',      # cardiac, trauma, medical, etc.
    'patient_age',         # affects severity significantly
    'population_density',  # proxy for access and call speed
    'weather',             # 0=clear to 3=blizzard
    'terrain',             # 0=flat to 3=water
    'has_landing_zone',    # 0 or 1
    'distance_to_hospital',# km
    'distance_to_vehicle', # km — nearest vehicle distance
    'response_time',       # predicted response time
    'season',              # 0=spring to 3=winter
    'hour_of_day',         # 0 to 23
]

# The actual input features (X) — severity is the label (Y)
INPUT_FEATURES = [
    'emergency_type',
    'patient_age',
    'population_density',
    'weather',
    'terrain',
    'has_landing_zone',
    'distance_to_hospital',
    'distance_to_vehicle',
    'response_time',
    'season',
    'hour_of_day',
]

# XGBoost hyperparameters
# These are standard starting values —
# your paper can include a hyperparameter
# tuning section using GridSearchCV
XGBOOST_PARAMS = {
    'n_estimators':     200,   # number of trees
    'max_depth':        6,     # max depth per tree
    'learning_rate':    0.1,   # how fast model learns
    'subsample':        0.8,   # fraction of data per tree
    'colsample_bytree': 0.8,   # fraction of features per tree
    'random_state':     42,    # reproducibility
    'eval_metric':      'mlogloss',
    'use_label_encoder': False,
}

# ── Data Loading ─────────────────────────────────────────────────
def load_training_data(csv_path=RESULTS_CSV_PATH):
    """
    Loads simulation results CSV and prepares it for
    ML model training.

    The CSV was generated by simulation/runner.py.
    Each row is one emergency dispatch decision.
    We use the MERLIN decisions as training data —
    because MERLIN's decisions are the ground truth
    we want the model to learn.

    Returns: (X, y, df) where
      X = feature matrix (numpy array)
      y = severity labels (numpy array)
      df = full dataframe for analysis
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(
            f"Training data not found at {csv_path}\n"
            f"Run simulation/runner.py first to generate data."
        )

    df = pd.read_csv(csv_path)

    # Filter to MERLIN decisions only
    # We train on MERLIN's decisions because they represent
    # the optimal dispatch choices we want to learn from
    merlin_df = df[df['system'] == 'MERLIN'].copy()

    print(f"Loaded {len(df)} total records")
    print(f"MERLIN records for training: {len(merlin_df)}")
    print(f"Severity distribution:")

    for sev in sorted(merlin_df['severity'].unique()):
        count = len(merlin_df[merlin_df['severity'] == sev])
        pct   = count / len(merlin_df) * 100
        name  = SEVERITY_NAMES[sev]
        print(f"  {name}: {count} ({pct:.1f}%)")

    print()

    # Build feature matrix X
    # Some features in INPUT_FEATURES may not be in the CSV
    # because they come from DispatchDecision.features
    # We use what's available and engineer the rest
    available_features = []
    for feat in INPUT_FEATURES:
        if feat in merlin_df.columns:
            available_features.append(feat)

    # Engineer missing features from available columns
    if 'season' not in merlin_df.columns:
        merlin_df['season'] = (merlin_df['tick'] // 131400) % 4
        available_features.append('season')

    if 'hour_of_day' not in merlin_df.columns:
        merlin_df['hour_of_day'] = (merlin_df['tick'] % 1440) // 60
        available_features.append('hour_of_day')

    if 'has_landing_zone' not in merlin_df.columns:
        merlin_df['has_landing_zone'] = 1
        available_features.append('has_landing_zone')

    # Fill any remaining missing features with 0
    for feat in INPUT_FEATURES:
        if feat not in available_features:
            merlin_df[feat] = 0
            available_features.append(feat)

    # Ensure consistent feature order
    X = merlin_df[INPUT_FEATURES].values
    y = merlin_df['severity'].values

    return X, y, merlin_df


def analyse_class_balance(y):
    """
    Checks if severity classes are balanced.
    Imbalanced classes are common in medical ML —
    critical cases are rare but important.

    Prints distribution and suggests handling strategy.
    """
    unique, counts = np.unique(y, return_counts=True)
    total = len(y)

    print("Class Balance Analysis:")
    print("-" * 40)
    for cls, count in zip(unique, counts):
        pct = count / total * 100
        bar = "█" * int(pct / 2)
        print(f"  {SEVERITY_NAMES[cls]:<10} {count:>4} "
              f"({pct:>5.1f}%) {bar}")

    min_pct = min(counts) / total * 100
    if min_pct < 5:
        print()
        print("⚠ Imbalanced classes detected.")
        print("  Minority class < 5% — consider:")
        print("  → class_weight parameter in XGBoost")
        print("  → SMOTE oversampling")
        print("  → Focus on recall for minority class")
    else:
        print()
        print("✓ Classes reasonably balanced.")
    print()

    # ── Model Training ───────────────────────────────────────────────
def train_severity_model(X, y, test_size=0.2,
                          random_state=42, verbose=True):
    """
    Trains an XGBoost classifier to predict emergency severity.

    Process:
    1. Split data 80% train / 20% test
    2. Train XGBoost on training set
    3. Evaluate on test set (model never saw this data)
    4. Report F1 score, precision, recall per class
    5. Return trained model and evaluation metrics

    The 80/20 split and evaluation methodology are
    described in your paper's methodology section.

    Returns: (model, train_metrics, test_metrics)
    """

    # ── Train/Test Split ─────────────────────────────────────────
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size    = test_size,
        random_state = random_state,
        stratify     = y   # ensures equal severity distribution
                           # in both train and test sets
    )

    if verbose:
        print("Training XGBoost Severity Classifier")
        print("-" * 45)
        print(f"Training samples: {len(X_train)}")
        print(f"Test samples:     {len(X_test)}")
        print()

    # ── Train Model ──────────────────────────────────────────────
    model = xgb.XGBClassifier(**XGBOOST_PARAMS)
    model.fit(
        X_train, y_train,
        eval_set              = [(X_test, y_test)],
        verbose               = False
    )

    # ── Evaluate on Training Set ─────────────────────────────────
    y_train_pred = model.predict(X_train)
    train_acc    = accuracy_score(y_train, y_train_pred)
    train_f1     = f1_score(y_train, y_train_pred,
                            average='weighted')

    # ── Evaluate on Test Set ─────────────────────────────────────
    y_test_pred = model.predict(X_test)
    test_acc    = accuracy_score(y_test, y_test_pred)
    test_f1     = f1_score(y_test, y_test_pred,
                           average='weighted')

    if verbose:
        print("Training Results:")
        print(f"  Train accuracy: {train_acc:.4f}")
        print(f"  Train F1 score: {train_f1:.4f}")
        print()
        print("Test Results (unseen data):")
        print(f"  Test accuracy:  {test_acc:.4f}")
        print(f"  Test F1 score:  {test_f1:.4f}")
        print()

        # Check for overfitting
        gap = train_acc - test_acc
        if gap > 0.10:
            print(f"⚠ Overfitting detected: "
                  f"train-test gap = {gap:.3f}")
            print("  Consider: reducing max_depth, "
                  "increasing subsample")
        else:
            print(f"✓ No overfitting: "
                  f"train-test gap = {gap:.3f}")
        print()

        # Per-class report
        print("Per-Class Performance:")
        print("-" * 45)
        target_names = [SEVERITY_NAMES[i] for i in range(4)]
        print(classification_report(
            y_test, y_test_pred,
            target_names=target_names,
            digits=3
        ))

        # Confusion matrix
        cm = confusion_matrix(y_test, y_test_pred)
        print("Confusion Matrix:")
        print("(rows=actual, cols=predicted)")
        header = f"{'':>10}" + "".join(
            f"{SEVERITY_NAMES[i]:>10}" for i in range(4)
        )
        print(header)
        for i, row in enumerate(cm):
            row_str = f"{SEVERITY_NAMES[i]:>10}"
            for val in row:
                row_str += f"{val:>10}"
            print(row_str)
        print()

    train_metrics = {
        'accuracy': train_acc,
        'f1_weighted': train_f1
    }
    test_metrics = {
        'accuracy': test_acc,
        'f1_weighted': test_f1,
        'y_test': y_test,
        'y_pred': y_test_pred
    }

    return model, train_metrics, test_metrics

# ── Feature Importance ───────────────────────────────────────────
def print_feature_importance(model, verbose=True):
    """
    Prints which features the model relies on most.

    Feature importance tells you:
    - Which variables most influence severity prediction
    - Whether the model learned sensible patterns
    - What to highlight in your paper's discussion section

    In MERLIN, we expect:
    - emergency_type → highest importance
    - patient_age    → second highest
    - terrain        → important for water cells

    If weather is highest → something is wrong
    (weather shouldn't determine severity)

    Returns: dict of feature → importance score
    """
    importances = model.feature_importances_
    feature_importance = dict(zip(INPUT_FEATURES, importances))

    # Sort by importance descending
    sorted_fi = sorted(
        feature_importance.items(),
        key=lambda x: x[1],
        reverse=True
    )

    if verbose:
        print("Feature Importance (XGBoost):")
        print("-" * 45)
        for feat, imp in sorted_fi:
            bar = "█" * int(imp * 50)
            print(f"  {feat:<25} {imp:.4f}  {bar}")
        print()

        # Sanity check
        top_feature = sorted_fi[0][0]
        if top_feature == 'emergency_type':
            print("✓ Top feature is emergency_type — expected.")
        else:
            print(f"⚠ Unexpected top feature: {top_feature}")
            print("  Review simulation data generation.")
        print()

    return feature_importance


# ── Model Save and Load ──────────────────────────────────────────
def save_model(model, path=MODEL_SAVE_PATH):
    """
    Saves trained model to disk using pickle.
    Allows model to be loaded without retraining.
    """
    with open(path, 'wb') as f:
        pickle.dump(model, f)
    print(f"Model saved to: {path}")


def load_model(path=MODEL_SAVE_PATH):
    """
    Loads previously saved model from disk.
    Used by dispatch engine in production.
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"No saved model at {path}\n"
            f"Run train_severity_model() first."
        )
    with open(path, 'rb') as f:
        model = pickle.load(f)
    print(f"Model loaded from: {path}")
    return model


def predict_severity(model, features_dict):
    """
    Predicts severity for one emergency given its features.

    This is the function called by the dispatch engine
    in real-time during simulation (and in deployment).

    Parameters:
      model         → trained XGBoost model
      features_dict → dict with keys matching INPUT_FEATURES

    Returns: (predicted_severity_int, confidence_scores)
    """
    # Build feature vector in correct order
    feature_vector = np.array([
        features_dict.get(feat, 0)
        for feat in INPUT_FEATURES
    ]).reshape(1, -1)

    # Predict class
    severity_pred = model.predict(feature_vector)[0]

    # Predict probabilities for each class
    probabilities = model.predict_proba(feature_vector)[0]
    confidence = {
        SEVERITY_NAMES[i]: round(float(p), 4)
        for i, p in enumerate(probabilities)
    }

    return int(severity_pred), confidence

# ── Main Training Pipeline ───────────────────────────────────────
def run_training_pipeline(csv_path=RESULTS_CSV_PATH,
                           save_path=MODEL_SAVE_PATH):
    """
    Full training pipeline — one function to run everything.

    Steps:
    1. Load simulation data
    2. Analyse class balance
    3. Train XGBoost model
    4. Print feature importance
    5. Save model to disk
    6. Test prediction on sample emergency

    This is what you run after generating new simulation data.
    """
    print("=" * 50)
    print("MERLIN Severity Model — Training Pipeline")
    print("=" * 50)
    print()

    # Step 1: Load data
    X, y, df = load_training_data(csv_path)

    # Step 2: Class balance
    analyse_class_balance(y)

    # Step 3: Train
    model, train_m, test_m = train_severity_model(
        X, y, verbose=True
    )

    # Step 4: Feature importance
    print_feature_importance(model)

    # Step 5: Save
    save_model(model, save_path)
    print()

    # Step 6: Test prediction
    print("Sample Prediction Test:")
    print("-" * 45)
    test_features = {
        'emergency_type':       0,    # Cardiac arrest
        'patient_age':          72,   # Elderly patient
        'population_density':   0.8,  # Town area
        'weather':              0,    # Clear
        'terrain':              0,    # Flat
        'has_landing_zone':     1,    # Landing zone available
        'distance_to_hospital': 45.0, # 45km from hospital
        'distance_to_vehicle':  22.0, # 22km from nearest vehicle
        'response_time':        20,   # Estimated 20 min
        'season':               3,    # Winter
        'hour_of_day':          14,   # 2pm
    }

    severity, confidence = predict_severity(model, test_features)

    print("Input: Cardiac arrest, age 72, winter, 45km from hospital")
    print(f"Predicted severity: {SEVERITY_NAMES[severity]}")
    print("Confidence scores:")
    for name, prob in confidence.items():
        bar = "█" * int(prob * 30)
        print(f"  {name:<10} {prob:.4f}  {bar}")

    print()
    print("=" * 50)
    print("Training pipeline complete.")
    print(f"Model saved to: {save_path}")
    print("=" * 50)

    return model, test_m